runtime: nodejs18

env_variables:
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
  NODE_ENV: "production"
  AGORA_APP_ID: "your-agora-app-id"
  AGORA_APP_CERTIFICATE: "your-agora-app-certificate"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /uploads
  static_dir: uploads
  secure: always

- url: /.*
  script: auto
  secure: always